<?php
/**
 * File Name: WechatMpMenuTemplateActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-26 11:38:36
 * @version: 4.0.4
 */

namespace qh4module\wechat\models\mpmenu;


use qttx\web\ActiveRecord;

/**
 * Class WechatMpMenuTemplateActiveRecord
 * @package qh4module\wechat\models\mp
 * @description 数据表tbl_project的ActiveRecord模型
 * @property string $id 
 * @property string $name 
 * @property int $is_used 
 * @property int $create_time 
 * @property int $del_time
 */
class WechatMpMenuTemplateActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%wechat_mp_menu_template}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
